version: '3.8'

services:
  test:
    build: ./test-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./test-service:/app
      - /app/node_modules